#!/bin/sh

PATH=${PATH}:/usr/bin:/usr/local/bin

hostname=localhost
resolution=600
papersize=a4
printer=BJF%%PRTYPE%%

GS="gs -q -r$resolution -dNOPROMPT -dSAFER \
      -sPAPERSIZE=$papersize -sDEVICE=bmp16m -sOutputFile=- -"
BJFILTER="bjfilter --model $printer --imageres $resolution --fit"

psselect -r | bjcmd "${GS} | ${BJFILTER}"
